### ISSUE TITLE
Issues with IMA SDK

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#364]
http://www.aktuelvizyon.com/sondakika-isvecte-2-saldiri-sehir-merkezinde-catismalar-basladi
https://github.com/reek/anti-adblock-killer/issues/3058

http://www.cbsnews.com/news/voter-fraud-case-tied-to-iowan-woman-voting-for-trump-twice/
#350

Added temporary whitelist until this issue is resolved.

**Comment by jspenguin2017** [comment]
Something is broken about this `[object Object]`. 
`||cbsnews.com/news/*/[object%20object]$image,redirect=1x1-transparent.gif`

**Comment by jspenguin2017** [comment]
It is not able to properly set the poster... 
![image](https://user-images.githubusercontent.com/7283682/27996324-05a5f0ba-649d-11e7-873b-89678cdd0e69.png)

**Comment by jspenguin2017** [comment]
I see the problem, Google's original SDK will modify the behavior of the poster... CBS is using some undocumented behavior of the SDK which causes the incompatibility.

**Comment by adreporter** [comment]
@jspenguin2017 Here's another website:

http://play.ludigames.com/games/nitroStreetRunFree/?ms_sid=4&sv13214=9neng1hv43wics0sx651&c=170

This is a game that doesn't work properly with your extension enabled. After hitting a car you should see:
<img width="328" alt="proof" src="https://user-images.githubusercontent.com/18214146/27998521-2eeb47ee-6511-11e7-9783-b1fcfdd7399f.PNG">

but I see this:
<img width="335" alt="cattura1111" src="https://user-images.githubusercontent.com/18214146/27998525-42a95a00-6511-11e7-90a0-c5f87154ce90.PNG">
I hear a sound every 15 seconds and I can't play anymore.

The console is full of these warnings:
<img width="960" alt="lol" src="https://user-images.githubusercontent.com/18214146/27998607-2ac375aa-6512-11e7-9c21-87897e98c493.PNG">

Top of the console:
<img width="960" alt="lol2" src="https://user-images.githubusercontent.com/18214146/27998637-77593c38-6512-11e7-98aa-6bf80a48470d.PNG">

**Comment by jspenguin2017** [comment]
Added logic to limit log count to 10.

**Comment by jspenguin2017** [comment]
Fixed. That was one embarrassing mistake...

**Comment by adreporter** [comment]
I think I found another website with issues with IMA SDK
http://www.fullmatchesandshows.com/2017/07/12/basel-vs-athletic-bilbao-highlights/
<img width="960" alt="etrewt" src="https://user-images.githubusercontent.com/18214146/28180243-d86fb7c8-6804-11e7-95b5-91cddd1eb233.PNG">
<img width="960" alt="werwerwr" src="https://user-images.githubusercontent.com/18214146/28180256-e132b9a0-6804-11e7-9787-7675f7a49b9c.PNG">
There's no play/pause button so if I click on the video it will pause it, but If I press again, instead of continuing playback, the video plays from the beginning. Can you reproduce?

**Comment by jspenguin2017** [comment]
Seems to work fine for me...

**Comment by adreporter** [comment]
Ok, try this please:
1) Open the link
2) Scroll down to the player
3) Go to fullscreen by clicking <img width="25" alt="aqsasa" src="https://user-images.githubusercontent.com/18214146/28211771-a7c8c520-689e-11e7-90db-d43b9e1be80e.PNG">
4) Let the video play for 10 seconds
5) Click twice on the video
6) You'll notice the video will start from beginning, instead of continuing playback

**Comment by jspenguin2017** [comment]
That's not an issue with my implementation, Google's real SDK does that as well.

**Comment by jspenguin2017** [comment]
Seems like blocking the SDK for this website is better.

**Comment by adreporter** [comment]
https://gitlab.com/xuhaiyang1234/AAK-Cont/issues/131
I was able to reproduce it yesterday, but now I can't. 
Anyway...
http://ladnydom.pl/inspiracje/1,153170,20421025,ognisko-w-ogrodzie-porady.html
I think this website has issues with IMA SDK.
Scrolling down the page slows down the tab.
Look what happens if I scroll down the page as fast as I can:
<img width="931" alt="eerer" src="https://user-images.githubusercontent.com/18214146/28504482-53470724-7018-11e7-87e3-f45c33f06a2c.PNG">
I noticed the more I scroll down, the more cpu and ram are being used.
I don't know if this will help, but I see this in the logger:
<img width="510" alt="aaa" src="https://user-images.githubusercontent.com/18214146/28504504-a5cf777e-7018-11e7-8e8e-44210368aef0.PNG">

**Comment by jspenguin2017** [comment]
I have added the white list so I can loopback from my extension. 
It uses more RAM and CPU if you scroll down fast because the webpage tries to load more content as you scroll.

**Comment by jspenguin2017** [comment]
Since the top part of the webpage does not unload, it will use more RAM, CPU usage will fall down if you stop scrolling. What lead you to believe it is caused by Extension?

**Comment by adreporter** [comment]
Sorry, you're right. It's caused by an extension called "I don't care about cookies". Without it, I can scroll down as fast as I can and it doesn't slow the page.
Next time before reporting a problem, I will see if there are any conflicts with another extension.
Sorry again.

**Comment by adreporter** [comment]
@jspenguin2017 
http://www.a10.com/snail-bob-games/blackjack-bet
After winning or losing a hand, I see this circle spinning for like 10 seconds
<img width="300" alt="asfdaf" src="https://user-images.githubusercontent.com/18214146/29242988-6f8513a4-7f95-11e7-9df6-e2da25a7bc60.PNG">
Does it have something to do with IMA SDK?

Screenshots of the Console:<details>
<img width="960" alt="part1" src="https://user-images.githubusercontent.com/18214146/29243017-e345e8ae-7f95-11e7-89de-59109b458194.PNG">
<img width="960" alt="part2" src="https://user-images.githubusercontent.com/18214146/29243018-e8a02936-7f95-11e7-87b6-9c6f1cd34dc3.PNG">
<img width="960" alt="part3" src="https://user-images.githubusercontent.com/18214146/29243019-ed63dad0-7f95-11e7-9507-222eaa6f3a17.PNG"> </details>
Could you please have a look?

**Comment by jspenguin2017** [comment]
Can't reproduce. The circle shows for like half a second and goes away for me.
