### ISSUE TITLE
anonymousemail.me

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#594]
### Test link (required): 
https://anonymousemail.me

### Screenshot of the web page (required): 
https://i.imgur.com/CWd3bJP.png
### Screenshot of the console (press `F12` to bring up the console) (required): 
https://i.imgur.com/jy6ndth.png

**Comment by uBlock-user** [comment]
Can't access the website. `GeoLocked`

**Comment by lain566** [comment]
It's broken

**Comment by jspenguin2017** [comment]
Hopefully this won't be another sticky website...

**Comment by lain566** [comment]
Yes, I think so, yes. We should not put clickable links, to avoid problems like these.

**Comment by jspenguin2017** [comment]
Hum... Yea, maybe we should block referer that goes out of GitHub...

**Comment by lain566** [comment]
Something like this 

```
<!--
Before opening an issue, you MUST read the contribution guideline. Failure to do so may result in a ban. 
-->

### Test link (required): 
https://jspenguin2017.github.io/AnonymousRedirect/redirect.html?url=PASTE_URL_HERE
```

**Comment by lain566** [comment]
Add it to your proprietary solution, looks like it's not going to stop.

**Comment by darkbasic** [comment]
Making everything proprietary is **not** the solution. On the contrary we should stop linking external websites from bug reports, this is **stupid**. It's like shouting "hey, we're blocking you, let's see if you can circumnvent it!".
Please clearly state in the bug reports template that direct links are forbidden and that they should be masked (for example using hxxp:// instead of http://).

**Comment by jspenguin2017** [comment]
Yea, you got a point. 
Clickable links are easier to use, but does have the side effect of disclosing referer. 
But I mean this project isn't that hard to find, not sure how much would it help. 

I know proprietary solutions is not preferred, but sometimes there just isn't another way.

**Comment by darkbasic** [comment]
It is easy to find indeed, but since just a few peoples use uBlockProtector it's unlikely that they will notice a difference and explicitely target it, unless you point such bug reports right in their face.
Keep using clickable links means more work for you and more proprietary code to avoid for me, but It's your choice anyway.

**Comment by lain566** [comment]
@darkbasic when I said `Proprietary Solution`, I was referring to this issue only, what solution does it propose to this issue?

**Comment by lain566** [comment]
It's broken for uBlock Protector, but it's fixed for adguard, they were watching you, only you.

**Comment by jspenguin2017** [comment]
That's easy to deal with, I'll just copy Adguard's solution, when they break it, they break both :D
