### ISSUE TITLE
a-o.ninja

### ISSUE THREAD

**Issue by mat41997** [jspenguin2017/uBlockProtector#637]
site
https://a-o.ninja/anime/maoyuu-maou-yuusha/1

img
![2017-10-05 04_05_16-maoyuu maou yuusha 02 pl online hd a-o ninja anime pl full hd online](https://user-images.githubusercontent.com/5884000/31208138-f06d26a2-a982-11e7-82dd-3169ba139c2f.png)

ub 1.14.8
ubpe 11.354
chrome 61.0.3163.100

**Comment by uBlock-user** [comment]
true url - https://tune.pk/player/embed_player.php?vid=6005549&folder=2015/04/23/&width=600&height=350&autoplay=no

**Comment by uBlock-user** [comment]
aa script - https://player.tune.pk/v2/js/master.full.min.js?v=08082017

**Comment by uBlock-user** [comment]
another one - https://player.tune.pk/v2/js/annoy.min.js

**Comment by uBlock-user** [comment]
mid-roll ads are also inserted by the player twice - https://i.gyazo.com/322c1c1d5dce641be00d39f64d247395.png

**Comment by jspenguin2017** [comment]
@uBlock-user Redirect rule needs to be limited to a specific domain. Like `||tune.pk/js/ads.js$script,redirect=noopjs`.

**Comment by jspenguin2017** [comment]
Nothing worked, let's just patch their ads request.

**Comment by uBlock-user** [comment]
@jspenguin2017 It is limited to tune.pk , I added a `$domain` directive for that reason only.

**Comment by uBlock-user** [comment]
My filter works perfectly 

![](https://i.gyazo.com/07a62541202432398b54b4ec9b0a9d8d.png)

**Comment by jspenguin2017** [comment]
It doesn't work for me. 
![image](https://user-images.githubusercontent.com/7283682/31320598-632cef2a-ac34-11e7-908b-854e64d7e508.png)

**Comment by uBlock-user** [comment]
Those yellow dots are parts where the scripts tries to make a connection to pull some ads but fails due to Easylist CSS filters, so you don't see any ads but those yellow dots will remain there which I still don't see as the issue as long as the ads are shown as the entire overlay is blocked. Another thing in my case, I couldn't even stream the video and was greeted by an anti adblock msg, which my filter patched it. 

Were you able to reproduce any anti adblock notice ? That was my issue in the first place.

**Comment by uBlock-user** [comment]
Also OP didn't do a good job of explaining whether he is seeing ads or facing an anti adblock notice, so I had to take up my own investigation into the website.

**Comment by jspenguin2017** [comment]
Whatever, it's patched in Extension and it's working as how I expect now.
