### ISSUE TITLE
dailymotion.com

### ISSUE THREAD

**Issue by mat41997** [jspenguin2017/uBlockProtector#727]
![2017-11-26 12_03_03-anime dragon ball super - odcinek 117 - kreskoweczki pl](https://user-images.githubusercontent.com/5884000/33239423-2041b86e-d2a2-11e7-8742-ca909c58c835.png)
`https://www.kreskoweczki.pl/kreskowka/100431/dragon-ball-super_odcinek-117`

steps to reproduce
- play the video

my filters
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.112
chrome 62.0.3202.94

**Comment by uBlock-user** [comment]
URL - `https://www.dailymotion.com/embed/video/k5BUXjUh13HesnpKTRo`

```
||$third-party,domain=dailymotion.com
@@||dmcdn.net$domain=dailymotion.com
```

@okiehsch

**Comment by jspenguin2017** [comment]
Need a repo steps.

**Comment by uBlock-user** [comment]
URL in question - dailymotion.com/embed/video/k5BUXjUh13HesnpKTRo

3rd video ad is displayed, solution is block all 3rd party crap except for dmcdn.net which is the only 3rd party connection needed. 

This is rather Easylist's job to block those ads.

**Comment by uBlock-user** [comment]
Adding `||amazonaws.com^$domain=dailymotion.com` also does the job if you don't want to block all 3rd party content.

**Comment by jspenguin2017** [comment]
This is an invalid issue as per [contribution guideline](https://github.com/jspenguin2017/uBlockProtector/blob/master/CONTRIBUTING.MD). 

You did not use the template and did not report missed ads to EasiList or uAssets first. 

Please make sure to read and understand the contribution guideline before opening another issue, otherwise, I would have no other choice than preventing you from interacting with this repository. Please treat this as a warning.
