### ISSUE TITLE
theguardian.com

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/uBlockProtector#728]
### Test link (required): 
https://www.theguardian.com/tv-and-radio/2017/aug/25/netflix-marijuana-strains-original-shows

### Screenshot of the web page (including address bar and extension icons) (required): 
![capture](https://user-images.githubusercontent.com/15007183/33241639-54c931cc-d296-11e7-9383-8df874cc8e66.PNG)

### Explain what was not right (optional if obvious): 
right now it's just a message if it doesn't fit criteria of this project please market it invalid and close it

**Comment by gotitbro** [comment]
@jspenguin2017 This shouldn't be blocked. Its not shown to adblock users specifically, it is shown to all users. A website should be allowed to ask for donations it is not related to adblock or anti-adblock.

It seems to be an annoyance which I don't think is the purpose of uBlock Protector.

**Comment by jspenguin2017** [comment]
Nano Defender will block *all* anti-adblock notice regardless if they are shown to all users. With the only exception being a notice for auto-starting mining wall. 
I see what you are saying, and it would be a clear cut if the phrase "advertising revenue is falling" is not there. Since it is ambiguous and it is already blocked, it won't be changed.
