### ISSUE TITLE
gadzetomania.pl

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/uBlockProtector#786]
### Test link (required): 

https://gadzetomania.pl/

### Screenshot of the console (press `F12` to bring up the console) (required): 

![capture](https://user-images.githubusercontent.com/15007183/34628912-17219324-f234-11e7-83d9-0f38126b8adb.PNG)

### Environment (Required): 

- Operating System and Version: Win 7 Pro
- Browser and Version: Firefox 57.0.4(64-bit)
- Adblocker and Version: 1.0.0.25

### Add everything else that you believe to be useful below (optional): 

same happens in Chrome 63.0.3239.132(64-bit)

**Comment by jspenguin2017** [comment]
`gadzetomania.pl##.modal__body-adblock`
@okiehsch

**Comment by okiehsch** [comment]
`gadzetomania.pl##script:inject(abort-on-property-write.js, __serviceAbModal)`
For polish sites it would probably be better to also report these kind of issues to https://github.com/MajkiIT/polish-ads-filter/issues, as they use extended filter syntax and are better
equipped to test any given site for possible breakage caused by such a filter.

**Comment by xxcriticxx** [comment]
there is issue already open on .pl list

**Comment by okiehsch** [comment]
Sorry, I missed that.
