### ISSUE TITLE
ma-x.org

### ISSUE THREAD

**Issue by Dibbyo456** [jspenguin2017/uBlockProtector#876]
### Test link (required):

http://ma-x.org/2018/01/27/fonelab-for-android-3-0-10-cracked-by-max/

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/37042010-c32f559c-211a-11e8-92a6-f030d11ca9ad.png)
@okiehsch

**Comment by okiehsch** [comment]
Fixed.

**Comment by jspenguin2017** [comment]
I'm hesitating on whether to make this rule generic... With the rule, it's 21~23 ms. I think it's still acceptable, so I added the rule. I definitely need to start trimming rules elsewhere though... 

![image](https://user-images.githubusercontent.com/7283682/37068837-fba6b3fe-216d-11e8-8779-c83bb142bd08.png)

I'll also make Nano to try-catch script snippets, so one bad rule won't blow up the rest.

**Comment by jspenguin2017** [comment]
I hope Chrome is smart enough to cache parsing of content script, because it is consuming over 10 ms just to parse the script... Also it takes an eternity to get the runtime, but it seems once it got, the next get from another extension would benefit from it. 

Counting the async part it's close to 30 ms. It's getting dangerously close to becoming a problem. 

![image](https://user-images.githubusercontent.com/7283682/37069128-24c2c650-216f-11e8-9556-956d73347bd5.png)
