### ISSUE TITLE
bild.de

### ISSUE THREAD

**Issue by Esokrates** [jspenguin2017/uBlockProtector#935]
### Test link:
https://www.bild.de

### Screenshot of the console (press `F12` to bring up the console) (required):
![screenshot from 2018-05-15 19-06-57](https://user-images.githubusercontent.com/17780185/40072153-306fad3e-5873-11e8-91dc-1e918d57138d.png)

### Explain what was not right (optional if obvious):
After a second content gets hidden and a german message asks to turn off the adblocker.

#### Environment (Required)

- Operating System and Version:  Debian sid
- Browser and Version:  Chromium 66.0.3359.139
- Nano Adblocker Version: 1.0.0.48
- Nano Defender Version: 14.24

#### Your filter lists (Required)
Nano Defender Integration ​​​​
Nano filters​​​​​​​​​
Nano filters – Timer bypassing 
uBlock filters​​​​​
uBlock filters – Badware risks​​​​​
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​

Adblock Warning Removal List
EasyList

EasyPrivacy

Malware Domain List
Malware domains

Fanboy’s Annoyance List

Peter Lowe’s Ad and tracking server list

**Comment by Esokrates** [comment]
Have you tried in incognito mode? In incognito mode it does not work 100% of the time.

**Comment by jspenguin2017** [comment]
@okiehsch 
This is super weird, the page tests for connection to `adnxs.com`, but the redirection code would crash when not in incognito mode, but doesn't crash otherwise. 
![image](https://user-images.githubusercontent.com/7283682/40075667-177025c2-583a-11e8-886a-1fee28145241.png)
![image](https://user-images.githubusercontent.com/7283682/40075672-1d67fdba-583a-11e8-91b6-5a9de560fea0.png)


Also reproduced with uBO. 
![image](https://user-images.githubusercontent.com/7283682/40075621-fda20cd2-5839-11e8-9517-941a147977fb.png)

**Comment by okiehsch** [comment]
I can't reproduce, regarding the filter`, gorhill added those so I can't tell the reasoning behind them, but they still work consistently on my end, I tested with Chrome/Chromium and Firefox in incognito mode.

**Comment by jspenguin2017** [comment]
@okiehsch You need to click 2~3 articles.

**Comment by okiehsch** [comment]
After the sixth or seventh different article
![unbenannt](https://user-images.githubusercontent.com/16838044/40088606-11a236a8-58a8-11e8-8e28-16eb7552e2fc.JPG)

**Comment by okiehsch** [comment]
Just fyi, there is no such request on my end, so that is probably why I can not reproduce.
![unbenannt](https://user-images.githubusercontent.com/16838044/40088941-ab7c463c-58a9-11e8-9f21-22bac97792c8.PNG)
