### ISSUE TITLE
I noticed the dropped firefox support

### ISSUE THREAD

**Issue by melnation-com** [jspenguin2017/uBlockProtector#953]
Not sure why but that's sad, what is the closest alternative to this though?

**Comment by jspenguin2017** [comment]
It's up to you to find.

**Comment by LiCybora** [comment]
@melnation-com I have forked it and build it unofficially for Firefox, signed with my Mozilla ID and keep pull request from here for update (with auto update). If it helps you may get it from my repo <a href="https://github.com/LiCybora/NanoDefenderFirefox">here</a>.

@jspenguin2017 Are you still looking for maintainers on other browsers? I may want to help keeping the Firefox port alive as I am mandatory to use Firefox. I may quite new to GitHub and may require time to learn, but I guess I am able to catch up updates and accept for browser-specific issue.
Anyway thanks for your product in the past day for Firefox build.

**Comment by jspenguin2017** [comment]
Your build is not correct, so it would not be considered for official port until the issue is resolved. You need to use NanoBuild to produce the correct build.

**Comment by LiCybora** [comment]
I build it from the NanoBuild with modified your Mozilla ID as mine. Do you mean I have to use --package method to sign and publish it?

**Comment by jspenguin2017** [comment]
You should do `node . --firefox --pack`. Your current manifest is not correct. You also want to pull the latest NanoBuild as it contained an error before.

**Comment by LiCybora** [comment]
Yes I also pull from latest NanoBuild. I guess my current manifest change only remove chromium-specific variable to Firefox one and append with my auto updater. I will revert back to yours and perhaps NanoBuild will do the job (and also revert to your NanoBuild).
If I just do `node . --firefox --pack` then this is unsigned and installable only for unbrand or developer version (as I can't sign with your Mozilla token). But I will do it if only unsigned version is supported.

**Comment by jspenguin2017** [comment]
You should add further changes to the manifest to your fork of NanoBuild. Some Chromium platform scripts are also used in the Firefox build.

**Comment by LiCybora** [comment]
OK. I have just made some change (Moz credentail, auto-updater and browser style to remove warning from console) to my fork of <a href="https://github.com/LiCybora/NanoBuild">NanoBuild</a>. I also revert my defender's manifest to your version. Now the only difference is the pop up font and background is explicitly set (Otherwise Firefox seems default to Time New Romance but not the case of Chromium). Also I put the official build example on release (but I cannot sign the example this time due to same version is signed before). You may check if now is corrected.
Moreover, is the same rule for being official port applies for NanoCore if I plan to maintain it as well?

**Comment by jspenguin2017** [comment]
For Nano Defender, here are my expectations / what you can expect from me: 
- You should produce correct, optimized, and optionally signed builds
- You should pull upstream updates and respond to my issues within 3 days
- I will accept and fix issues from users using official ports, pull requests are also welcomed
  - You should also accept issues from your users, and forward them to me or submit pull requests if appropriate
- I will accept Quick Issue Reports from users of official ports

---

I have verified your new build and it is still not correct. You should not override the manifest produced by NanoBuild. 

---

For Nano Adblocker things become really complicated. There is no working build system. Nano Build is likely to be already outdated. You have to read gorhill's new build scripts and transform them to fit Nano Adblocker. 

Your port would be considered official if: 
- You produced stable builds without regressions or compromises
- You implemented integration with Nano Defender
- You will pull upstream updates within 30 days
- You will address critical issues within 7 days
- You will accept all issues from your users
  - I will also accept issues from users using official ports, but I will only forward them on

**Comment by LiCybora** [comment]
> I have verified your new build and it is still not correct. You should not override the manifest produced by NanoBuild.

I just run `node . --firefox --pack` and upload it without overriding things. I clone both your NanoBuild and uBlockProtector and build directly, and diff with my new build got only this:

```
19c19,20
<     "default_title": "Nano Defender"
---
>     "default_title": "Nano Defender",
>     "browser_style": false
64c65,66
<       "id": "{6ea144f3-db99-47f4-9a1d-815e8b3944d1}",
---
>       "id": "{f9cacf2e-cafc-4f0f-b6ad-8e1a01b4b4d0}",
>       "update_url": "https://raw.githubusercontent.com/LiCybora/NanoDefenderFirefox/master/Extension%20Compiler/updates.json",
```
They are just different moz-id (my id instead), an auto-updater and browser_style just remove the console warning (may remove it, seems no side effect in my trial). They are comes from further changes in my fork of Nano Build:
![screenshot-2018-6-17 nanoadblocker nanobuild](https://user-images.githubusercontent.com/40160522/41504550-3f256d84-7225-11e8-8673-c87ef031b613.png)
That's all changed in my forked Nano Build related to Nano Defender. 

Do you mean the incorrect is [this](https://github.com/LiCybora/NanoDefenderFirefox/blob/master/src/manifest.json)? This is just comes from directly forked before being built and not used in the real release. I may upload built source code instead of origin source from forked if this is the issue.

> Nano Build is likely to be already outdated. You have to read gorhill's new build scripts and transform them to fit Nano Adblocker.

I may need more testing to make sure it works correctly as you mentioned the recent updates have regression in latest Firefox in the past. Maybe I work for Nano Defender first.

**Comment by jspenguin2017** [comment]
Eh, my bad. The build script was broken. It should be good now.

**Comment by LiCybora** [comment]
Updated from upstream and thx. If everything good, I will publish and sign the new version and edit my README.MD as official.

**Comment by jspenguin2017** [comment]
Yep, that looks good now.

**Comment by jspenguin2017** [comment]
Let me know when you think it is stable enough, I'll link it on the home page.

**Comment by LiCybora** [comment]
Thx. I updated the README.MD and tested on most sites seems working. It should be stable. In case any issues I will fix it asap.
