### ISSUE TITLE
doesnt work: Extra installation steps for uBlock Origin

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [jspenguin2017/uBlockProtector#954]
the instructions doesnt work:

Extra installation steps for uBlock Origin

Step 1. Enable Adblock Warning Removal List.

Step 2. Install Nano Defender Integration filter list.

Step 3. Go to uBlock Origin dashboard, select "Settings" tab, check "I am an advanced user", click the gears that shows up, replace "unset" after "userResourcesLocation" by "https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoResources.txt" (without quotes).

Note: If you have another User Resources in use, then you would need to either switch to Nano Adblocker or manually merge resources. It takes an eternity to get any resources into uAssets, I have tried.

Step 4. Install Nano filters.

Step 5. Install Nano filters - Whitelist.

---

when you click the link for each step, it shows a whitescreen

when you copy paste it, it searches what you copy/paste into whichever is your default search for chrome

**Comment by jspenguin2017** [comment]
Can't reproduce. Make sure you are using an up-to-date build of uBO. 
![image](https://user-images.githubusercontent.com/7283682/41512773-744b2a68-724c-11e8-92d1-036f45fa7e6f.png)

**Comment by spodermenpls** [comment]
@jspenguin2017 What makes those extra installations steps necessary? I am using Nano Defender with uBlock Origin without those modifications for a long time now, and it works flawlessly, as far as I can tell.

**Comment by jspenguin2017** [comment]
@spodermenpls If you are happy with your setup, you are free to keep it that way. However, when things break, do not report it to me.

**Comment by Kovaelin** [comment]
@jspenguin2017 Do the order of the extra steps matter? I accidentally skipped Step 2 until the end. Thank you.

**Comment by jspenguin2017** [comment]
@Kovaelin That should still work.

**Comment by spodermenpls** [comment]
@jspenguin2017 Since the Adblock Warning Removal List has been kicked out of uBlock Origin's stock filters for a while now, I've wondered what makes that tiny list necessary for Nano Defender's operations? Do things break/deteriorate without it, or is it just recommended for unlikely cosmetic benefits?

**Comment by jspenguin2017** [comment]
@spodermenpls 

It has over 700 rules, so I do not consider it to be tiny. From my observation, it is updated from time to time, and I can confirm that it is useful on a few occasions. Depending on the websites you visit, it may or may not be useful, but in general, you are recommended to subscribe to it. 

Note that currently, if an anti-adblock issue is fixed by it, the issue will not be fixed again in Nano Defender nor Nano Filters.

**Comment by jspenguin2017** [comment]
@spodermenpls 

It has over 700 rules, so I do not consider it to be "tiny". From my observations, it is updated from time to time, and I can confirm that it is useful on a few occasions. Depending on the websites you visit, it may or may not be useful to you. But in general, you are recommended to subscribe to it. 

Note that currently, if an anti-adblock issue is fixed by it, the issue will not be fixed again in Nano Defender nor Nano Filters.

**Comment by spodermenpls** [comment]
@jspenguin2017 Maybe "antiquated" would be a more precise descriptor. The whole concept of "please deactivate voluntarily" notifications, this list's sole purpose, has been replaced pretty much entirely with strict anti-access techniques by now (be it via scripts or paywalls), at least in case of commercially operated websites. There are some sites in the wild that still benefit from this list, but the list of these is indeed tiny. If you inspect the filter rules, you'll notice that most site-specific rules apply to Russian and French sites, and also a considerable amount of websites being offline as a whole or having changed their deployment of notices, without changes being made to the list, which subsequently led to Raymond Hill's decision to deem it "obsolete" and remove it.

I am mentioning this, since your installation guide advises one to activate it literally as step number one, maybe it's time to adjust the verbage to a more "it's recommended to" approach, to not misguide users into thinking it might be necessary - as I did for a while. 😄

The issues solved by the list are solely cosmetic in nature anyway, so these are more appropriate to be addressed in Annoyances filter lists, which is being done a million times more thorough and frequent than this list ever did.

**Comment by mapx-** [comment]
`Adblock Warning Removal` List - "invented" by ABP - is completely useless. 
uBO is fixing the soft anti adb (warnings) in its own list (uBO annoyance list)

**Comment by jspenguin2017** [comment]
AWRL is updated from time to time, from my observation, a few rules are added or changed every few weeks. I agree that it is not as actively maintained as EasyList for example, but I do not think it is completely obsolete yet. Gorhill removed it from uBO's assets manifest because uBO has its own uBlock annoyance filter that generally supersedes AWRL. 

Unfortunately, uBlock annoyance is a big bundle of many different things. From newsletter sign up to anti-right-click to... [snow falling](https://github.com/uBlockOrigin/uAssets/commit/d1bbe4df7c14133e827cc8fb1d92046a1b26abf0)? The filter does too many things that a normal user would not expect. For this reason, I currently cannot replace AWRL with uBlock annoyance. 

Nano Defender does not have the notion of soft anti-adblock (which you seem to refer to them as "cosmetic in nature" anti-adblock). Unlike uAssets, all anti-adblock are treated equally here. If uAssets splits soft anti-adblock fixes into its own filter, I would immediately replace AWRL without hesitation. But until that day, I think the current installation steps are appropriate.

**Comment by llacb47** [comment]
Yeah, there probably needs to be some stricter standards for annoyances list.

**Comment by spodermenpls** [comment]
@jspenguin2017 OK, I see where you're coming from, thanks for elaborating. This is then more so a matter of "clash of philosophies" (uBlock ≠ AdGuard ≠ Nano..) than a case of "instructions having been untouched since first draft from years ago". 😄
